version: "3.9"

services:
  gateway:
    build:
      context: .
      dockerfile: Dockerfile.gateway
    container_name: gateway
    ports:
      - "5000:5000"
    networks:
      - microservices-net
    environment:
      - USER_SERVICE_URL=http://user-service:5001
      - PRODUCT_SERVICE_URL=http://product-service:5002
      - ORDER_SERVICE_URL=http://order-service:5003
      - PAYMENT_SERVICE_URL=http://payment-service:5004

  user-service:
    build:
      context: .
      dockerfile: Dockerfile.user
    container_name: user-service
    ports:
      - "5001:5001"
    networks:
      - microservices-net
    volumes:
      - ./services/user-service/database:/app/database
    environment:
      - USER_SERVICE_URL=http://user-service:5001
      - PRODUCT_SERVICE_URL=http://product-service:5002
      - ORDER_SERVICE_URL=http://order-service:5003
      - PAYMENT_SERVICE_URL=http://payment-service:5004
    depends_on:
      - gateway
    
  product-service:
    build:
      context: .
      dockerfile: Dockerfile.product
    container_name: product-service
    ports:
      - "5002:5002"
    networks:
      - microservices-net
    volumes:
      - ./services/product-service/database:/app/database
    environment:
      - USER_SERVICE_URL=http://user-service:5001
      - PRODUCT_SERVICE_URL=http://product-service:5002
      - ORDER_SERVICE_URL=http://order-service:5003
      - PAYMENT_SERVICE_URL=http://payment-service:5004
    depends_on:
      - gateway


  order-service:
    build:
      context: .
      dockerfile: Dockerfile.order
    container_name: order-service
    ports:
      - "5003:5003"
    networks:
      - microservices-net
    volumes:
      - ./services/order-service/database:/app/database
    environment:
      - USER_SERVICE_URL=http://user-service:5001
      - PRODUCT_SERVICE_URL=http://product-service:5002
      - ORDER_SERVICE_URL=http://order-service:5003
      - PAYMENT_SERVICE_URL=http://payment-service:5004
    depends_on:
      - gateway
      
  payment-service:
    build:
      context: .
      dockerfile: Dockerfile.payment
    container_name: payment-service
    ports:
      - "5004:5004"
    networks:
      - microservices-net
    volumes:
      - ./services/payment-service/database:/app/database
    environment:
      - USER_SERVICE_URL=http://user-service:5001
      - PRODUCT_SERVICE_URL=http://product-service:5002
      - ORDER_SERVICE_URL=http://order-service:5003
      - PAYMENT_SERVICE_URL=http://payment-service:5004
    depends_on:
      - gateway


networks:
  microservices-net:
    driver: bridge